name: Build

on: 
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths-ignore:
  #     - 'README.md'
  # pull_request:
  #   branches: [main]
  #   paths-ignore:
  #     - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@v3
        with:
          name: action.yml
          path: action.yml
      # TODO: add git push to commit dist/index.js